### ISSUE TITLE
New Hampshire

### ISSUE THREAD

**Issue by kcoronel** [hackforla/ballotnav-states#39]
### Overview
The database or data has some formatting or other issues that need to be resolved before it can be imported.

### Action Items
- [x] Data Collection Design
   - [x] Review Secretary of State Website
   - [x] Call a County starting from the first until you reach one that can validate the data with you.
      - [x] Checking the data that we have is correct
      - [x] Gathering data for fields that are empty
      - [x] Asking if there is anything else we should know
   - [x] Update Location Validation Test Sheet
   - [x] Edit the issue Action Items to reflect findings
- [x] Data Scientist/Scrapers
   - [x] Add the following columns to your data schema
     - [x] has_dropoff_location
     - [x] has_phone_number 
     - [x] state_2 (more details below) 
     - [x] inactive 
     - [x] hours 
     - [x] rules 
     - [x] display_notes
     - [x] where
     - [x] start_date
     - [x] accessibility
   - [x] Delete the following fields
      - [x] record_number 
      - [x] county_state
      - [x] name 
     - [x] scrapper 
     - [x] social
     - [x] locations_copy_4
     - [x] ballot_drop_off_location
     - [x] volunteers_validation_copy
     - [x] volunteers_scraper_copy
   - [x] Rename the following fields
     - [x] validate_url to source_data
- [x] add 603 area code to phone numbers 
   - [x] If Hours are available add them to the sheet by using the following convention (removing any info about days they are closed e.g. closed sat and sun, unless it refers to a specific date they are closed):
MONDAY-FRIDAY:1:00 PM-4:30PM  or Monday-Friday:7:00-12:00
- [x] Address fields needs to be broken up into individual components (address_1 and address_2) 
   - address_1 = Street name and address #
   - address_2 = suite # or room #, etc
   - city = city name
   - state = state name spelled out
   - state_2 = two-letter abbreviation for the address (for some states the location is in a different state than the voting district (crazy I know.  But this is why there is a state field separate which is supposed to be the state spelled out and that is the jurisdiction, not the physical location)

### Resources
[Google Sheet](https://docs.google.com/spreadsheets/d/1xUpK9QtxtzJv0dsTu7OzjfUu3TxcG_fZsbanQ4i5KgI/edit?usp=sharing)

**Comment by kcoronel** [comment]
**Is there a deadline for returning my absentee ballot?**
Yes. But it depends on whether you plan to mail your ballot or deliver it in-person.

If you’re mailing your absentee ballot, it needs to arrive to your local clerk by 5 p.m. on Election Day in order to be counted, according to New Hampshire law. This is different from some other states, which allow ballots to be counted if they are postmarked by the day of the election. Election officials recommend mailing absentee ballots as soon as possible, but at least two weeks before the election, to be sure it arrives on time.

If you’re delivering your own absentee ballot to your local clerk in-person, you should aim to drop it off by 5 p.m. on Election Day. You can also have someone else drop off your absentee ballot for you, in certain circumstances.

But if you can't make it to your local polling place by 5 p.m. on Election Day, you can still show up at the polls and cast an absentee ballot without going inside any time before the polling place closes, according to Associate Attorney General Nick Chong Yen.

"That voter, if they're feeling concerned about timing or being able to send [their ballot] through the mail, can appear at the polling place and utilize something called accessible voting on Election Day, which existed in our law prior to this whole public health crisis," Chong Yen told NHPR's The Exchange. 

Under this option, a voter can ask pollworkers to bring absentee ballot paperwork to them outside the polling place on Election Day. According to the state's election rules, "The absentee ballot delivered by the town or ward clerk shall be processed using the same procedures as any other absentee ballot except that the cutoff time [of 5 p.m. on Election Day] shall not apply.” 

**Can I return my ballot to a special "dropbox" before the election?**
It depends on where you live. Cities and towns are allowed to set up secure dropboxes at their local clerk’s offices to allow voters to deliver their absentee ballots before Election Day.

**Can I ask someone else to return my absentee ballot for me?**
Yes, but only if they meet the definition of a state-approved “delivery agent,” according to the election procedure manual.

You can ask your spouse, parent, sibling, child, grandchild, father-in-law, mother-in-law, son-in-law, daughter-in- law, stepparent or stepchild to return your absentee ballot for you. If you live in a nursing home or residential care facility, the administrator or administrator’s designee can return your ballot. According to the state, “This type of delivery agent is limited to delivering no more than 4 absentee ballots in any election.” If you require assistance completing your absentee ballot, the person who helps you can deliver it on your behalf. 

[NH 2020 elections](https://www.nhpr.org/post/2020-elections-guide-how-vote-absentee-or-polls-nh-during-covid-19#NON%20MAIL%20ABSENTEE%20OPTIONS)

**Comment by kcoronel** [comment]
@ExperimentsInHonesty @Arjayellis unsure if this is done since it doesn't have addresses - this is how the state lists [clerk details](https://app.sos.nh.gov/Public/ClerkDetails.aspx)

**Comment by aNullValue** [comment]
Note for the future: New Hampshire processing is an atypical case (will require manual jurisdiction rebuild) so I should handle its import personally.

**Comment by aNullValue** [comment]
New Hampshire has been processed from data I gathered directly from the NH SOS website (after reformatting).
