### ISSUE TITLE
Utah 

### ISSUE THREAD

**Issue by kcoronel** [hackforla/ballotnav-states#51]
### Overview
The database or data has some formatting or other issues that need to be resolved before it can be imported.

### Action Items
- [x] Data Collection Design
   - [x] Review Secretary of State Website
   - [x] Call a County starting from the first until you reach one that can validate the data with you.
      - [x] Checking the data that we have is correct
      - [x] Gathering data for fields that are empty
      - [x] Asking if there is anything else we should know
   - [x] Update Location Validation Test Sheet
   - [x] Edit the issue Action Items to reflect findings
- [x] Data Scientist/Scrapers
   - [x] Add the following columns to your data schema
      - [x] display_notes
      - [x] where
      - [x] start_date
      - [x] accessibility
   - [x] Delete the following fields
      - [x] field 23 
      - [x] latitude 
      - [x] longitude 
      - [x] social
      - [x] state and counties and county reps copy
   - [x] Rename the following fields
      - [x] state to state_2
      - [x] validate_url to source_data
   - [x] If Hours are available add them to the sheet by using the following convention (removing any info about days they are closed e.g. closed sat and sun, unless it refers to a specific date they are closed):
MONDAY-FRIDAY:1:00 PM-4:30PM  or Monday-Friday:7:00-12:00
- [x] Address fields needs to be broken up into individual components (address_1 and address_2) 
   - address_1 = Street name and address #
   - address_2 = suite # or room #, etc
   - city = city name
   - state = state name spelled out
   - state_2 = two-letter abbreviation for the address (for some states the location is in a different state than the voting district (crazy I know.  But this is why there is a state field separate which is supposed to be the state spelled out and that is the jurisdiction, not the physical location)

### Resources
[Google Sheet](https://docs.google.com/spreadsheets/d/11gztIV27vdAa3MUCoFhrOnczKFlYSy5UgUixr-37dVc/edit?usp=sharing)

**Comment by kcoronel** [comment]
This doesn't list all of Utah's locations I used the following random address: 290 W 100 NWashington, UT 84780
 in [Utah's voter system](https://votesearch.utah.gov/voter-search/resident/home), and it gave me drop off locations not listed in our scrape.

**Comment by kcoronel** [comment]
@aNullValue data is clean here but I found that we didn't have all the drop boxes and no central location to scrape them

**Comment by aNullValue** [comment]
@kcoronel if it's as good as we can get it, move it to ready-for-import

**Comment by aNullValue** [comment]
Utah has been processed
