### ISSUE TITLE
Rhode Island

### ISSUE THREAD

**Issue by Arjayellis** [hackforla/ballotnav-states#54]
### Overview
The database or data has some formatting or other issues that need to be resolved before it can be imported.

### Action Items
- [x] Data Quality
   - [x] Review Secretary of State Website
   - [x] Call a County starting from the first until you reach one that can validate the data with you.
      - [x] Checking the data that we have is correct
      - [x] Gathering data for fields that are empty
      - [x] Asking if there is anything else we should know
   - [x] Update Location Validation Test Sheet
   - [x] Edit the issue Action Items to reflect findings
- [ ] Data Scientist/Scrapers
- [ ] Add the following columns to your data schema
   - [ ] display_notes
   - [ ] where
   - [ ] start_date
   - [ ] accessibility
- [ ] Delete the following fields
   - [ ] latitude
   - [ ] longitude
   - [ ] social
   - [ ] state and counties and county reps copy
- [ ] Rename the following fields
   - [ ] Field 23 to location_name
   - [ ] validate_url to source_data
   - [ ] If Hours are available add them to the sheet by using the following convention (removing any info about days they are closed e.g. closed sat and sun, unless it refers to a specific date they are closed):
MONDAY-FRIDAY:1:00 PM-4:30PM  or Monday-Friday:7:00-12:00
- [ ] Address fields needs to be broken up into individual components (address_1 and address_2) 
   - address_1 = Street name and address #
   - address_2 = suite # or room #, etc
   - city = city name
   - states = state field will be the state spelled out, and state_2 will be the two letter abbreviation. For the address, need two-letter abbreviations. For some states, the location is in a different state than the voting district. 

### Resources/Instructions
[Google sheet](https://docs.google.com/spreadsheets/d/1-EvNO2yCPPJPZm15Qu36BFsMUt4GrrJoMS4R1zP2Ufk/edit#gid=1976013639)

**Comment by aNullValue** [comment]
Could this issue be altogether deleted?
