### ISSUE TITLE
South Dakota 

### ISSUE THREAD

**Issue by kcoronel** [hackforla/ballotnav-states#55]
### Overview
The database or data has some formatting or other issues that need to be resolved before it can be imported.

### Action Items
- [x] Data Collection Design
   - [x] Review Secretary of State Website
   - [x] Call a County starting from the first until you reach one that can validate the data with you.
      - [x] Checking the data that we have is correct
      - [x] Gathering data for fields that are empty
      - [x] Asking if there is anything else we should know
   - [x] Update Location Validation Test Sheet
   - [x] Edit the issue Action Items to reflect findings
- [x] Data Scientist/Scrapers
   - [x] Add the following columns to your data schema
      - [x] display_notes
      - [x] where
      - [x] start_date
      - [x] accessibility
   - [x] Delete the following fields
      - [x] field 23 
      - [x] latitude 
      - [x] longitude 
      - [x] social
      - [x] state and counties and county reps copy
   - [x] Rename the following fields
      - [x] validate_url to source_data
   - [x] If Hours are available add them to the sheet by using the following convention (removing any info about days they are closed e.g. closed sat and sun, unless it refers to a specific date they are closed):
MONDAY-FRIDAY:1:00 PM-4:30PM  or Monday-Friday:7:00-12:00
- [x] Address fields needs to be broken up into individual components (address_1 and address_2) 
   - address_1 = Street name and address #
   - address_2 = suite # or room #, etc
   - city = city name
   - state = state name spelled out
   - state_2 = two-letter abbreviation for the address (for some states the location is in a different state than the voting district (crazy I know.  But this is why there is a state field separate which is supposed to be the state spelled out and that is the jurisdiction, not the physical location)

### Resources
[Google Sheet](https://docs.google.com/spreadsheets/d/1_6bBNUpHhq5Tyv5fPlqkmB2q0EMb2TTPcMILizhjAcI/edit?usp=sharing)

**Comment by kcoronel** [comment]
@Seymour100 can you please update the data with this information that lists physical addresses  [2020CountyAuditorContactListWithPhysicalAddress](https://sdsos.gov/elections-voting/assets/2020CountyAuditorContactListWithPhysicalAddress.pdf)

**Comment by Seymour100** [comment]
@kcoronel , it looks like there are counties in this file that are not in the orginal file, and there are counties in the original file that aren't in this one. So I created new columns: county_new, match, address_1_new, and address_2_new. The "..._new" columns are all from the link you provided above.

**Comment by kcoronel** [comment]
@aNullValue how should I edit the data schema from Seymour's comment above

**Comment by aNullValue** [comment]
Make sure that the data from column A is appropriately represented in columns E,F. Once that's done, delete column A. Then you can move it to ready-to-import.

**Comment by aNullValue** [comment]
South Dakota is processed.
