### ISSUE TITLE
Arkansas

### ISSUE THREAD

**Issue by Arjayellis** [hackforla/ballotnav-states#58]
### Overview
The database or data has some formatting or other issues that need to be resolved before it can be imported.

### Action Items
- [X] Data Collection Design
   - [X] Review Secretary of State Website
   - [X] Call a County starting from the first until you reach one that can validate the data with you.
      - [X] Checking the data that we have is correct
      - [X] Gathering data for fields that are empty
      - [X] Asking if there is anything else we should know
   - [X] Update Location Validation Test Sheet
   - [X] Edit the issue Action Items to reflect findings

### Resources
[Google Sheet](https://docs.google.com/spreadsheets/d/1w0do2MiAbhVfUyF0-c6YskWRLv_xgQ9_-JoF2apq528/edit#gid=1790281819)

**Comment by aNullValue** [comment]
Arkansas has been processed.
