### ISSUE TITLE
Colorado

### ISSUE THREAD

**Issue by Arjayellis** [hackforla/ballotnav-states#6]
### Overview
The database or data has some formatting or other issues that need to be resolved before it can be imported.

### Action Items
- [X] Data Collection Design
   - [X] Review Secretary of State Website
   - [X] Call a County starting from the first until you reach one that can validate the data with you.
      - [X] Checking the data that we have is correct
      - [X] Gathering data for fields that are empty
      - [X] Asking if there is anything else we should know
   - [X] Update Location Validation Test Sheet
   - [X] Edit the issue Action Items to reflect findings
- [x] Data Scientist/Scrapers
   - [x] Add the following columns to your data schema
      - [x] display_notes
      - [x] where
      - [x] start_date
      - [x] accessibility
      - [x] state_2 (instructions to follow below)
   - [x] Delete the following fields
      - [x] record_number
      - [x] county_state
      - [x] name
      - [x] social
      - [x] scraper
      - [x] locations_copy
      - [x] volunteers_scraper_copy
      - [x] volunteers_validations_copy
   - [x] Rename the following fields
      - [x] ballot_dropoff_location to has_dropoff_location 
      - [x] validate_url to source_data
   - [x] If Hours are available add them to the sheet by using the following convention (removing any info about days they are closed e.g. closed sat and sun, unless it refers to a specific date they are closed):
MONDAY-FRIDAY:1:00 PM-4:30PM  or Monday-Friday:7:00-12:00
- [x] Address fields needs to be broken up into individual components (address_1 and address_2) 
   - address_1 = Street name and address #
   - address_2 = suite # or room #, etc
   - city = city name
   - state = state name spelled out
   - state_2 = two-letter abbreviation for the address (for some states the location is in a different state than the voting district (crazy I know.  But this is why there is a state field separate which is supposed to be the state spelled out and that is the jurisdiction, not the physical location)

### Resources
[Google Sheet](https://docs.google.com/spreadsheets/d/1ZIZwtstKq75UW4Q15eb9REhwZLTcKYZq8sZcRnUajMU/edit#gid=696706768)

**Comment by kcoronel** [comment]
I believe each county has a list of drop off locations, I found some for [Jefferson County](https://www.jeffco.us/3907/Find-Voting-Locations), [Larimer County](https://www.larimer.org/clerk/elections/voting-locations#/map/ALL), etc. but I haven't found an entire list @Arjayellis @ExperimentsInHonesty

**Comment by kcoronel** [comment]
@aNullValue the data for this is as good as we can have it however we don't have a list of drop off locations for all counties, let me know how you want us to proceed.

**Comment by aNullValue** [comment]
@kcoronel If it's as good as we can get it for now, go ahead and send it to ready-for-import and I'll get it imported.

**Comment by aNullValue** [comment]
Colorado has been processed
