### ISSUE TITLE
Washington

### ISSUE THREAD

**Issue by Arjayellis** [hackforla/ballotnav-states#9]
### Overview
The database or data has some formatting or other issues that need to be resolved before it can be imported.

### Action Items
- [x] Data Quality
   - [x] Review Secretary of State Website
   - [x] Call a County starting from the first until you reach one that can validate the data with you.
      - [x] Checking the data that we have is correct
      - [x] Gathering data for fields that are empty
      - [x] Asking if there is anything else we should know
   - [x] Update Location Validation Test Sheet
   - [x] Edit the issue Action Items to reflect findings
- [x] Data Scientist/Scrapers
 - [x] Add the following columns to your data schema
   - [x] display_notes
   - [x] where
   - [x] start_date
   - [x] accessibility
 - [x] Delete the following fields
   - [x] latitude
   - [x] longitude
   - [x] social
   - [x] state and counties and county reps copy
 - [x] Rename the following fields
   - [x] Field 23 to location_name
   - [x] validate_url to source_data
 - [x] Address fields needs to be broken up into individual components (address_1 and address_2) 
   - address_1 = Street name and address #
   - address_2 = suite # or room #, etc
   - state = state name spelled out
   - city = city name
   - state_2 =  two-letter abbreviation. For the address, need two-letter abbreviations. For some states, the location is in a different state than the voting district (crazy I know.  But this is why there is a state field separate which is supposed to be the state spelled out and that is the jurisdiction, not the physical location)

### Resources/Instructions
[Google sheet](https://docs.google.com/spreadsheets/d/1KsDfPoQMbnL6oixiLu5vcMe_1qm1_UEuJqQY0QVNYlU/edit#gid=1346103832)

**Comment by kcoronel** [comment]
The Elections Division is open for curbside service. Please call (360) 902-4180 for assistance, M - F 8 a.m. 5 p.m.
November 3 General Election - Deposit your ballot in an official drop box by 8 p.m. on Election Day.

**Comment by kcoronel** [comment]
@Arjayellis @ExperimentsInHonesty should I add this list of drop off boxes to the scraped data? https://www.sos.wa.gov/_assets/elections/ballot%20drop%20boxes%202019%20general%20election.pdf

**Comment by Arjayellis** [comment]
@aNullValue Is there an easy way to transfer the data at that link Karen posted into an excel document? That's the information we want.

**Comment by aNullValue** [comment]
That link Karen posted was actually to the _2019_ election information, so is not relevant for this election.

That said, I found links that are relevant, downloaded them, and reformatted. I saved the spreadsheets as new tabs in the google spreadsheet. Then I processed them.
